<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8pbixv0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8pbixv0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container8pbixv0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container8pbixv0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container8pbixv0\appDevDebugProjectContainer(array(
    'container.build_hash' => '8pbixv0',
    'container.build_id' => '6f794709',
    'container.build_time' => 1544805865,
), __DIR__.\DIRECTORY_SEPARATOR.'Container8pbixv0');
